### ISSUE TITLE
Color problem

### ISSUE THREAD

**Issue by ghost** [techbliss/x64dbg_orange_mod#1]
If possible, please change the colors regarding the area marked with red boxes so that the text is more visible.
![untitled-1](https://cloud.githubusercontent.com/assets/17880848/21286084/5604272a-c470-11e6-9765-ddfcf937e46e.png)

BTW the style is really cool, thanks for your work

**Comment by techbliss** [comment]
thx i will take alook today

**Comment by ghost** [comment]
Fix looks great! Thanks
