### ISSUE TITLE
Styling Errors

### ISSUE THREAD

**Issue by ghost** [techbliss/x64dbg_orange_mod#2]
Please have a look at the following issues:-

https://github.com/x64dbg/x64dbg/issues/1382
https://github.com/x64dbg/x64dbg/issues/1381
https://github.com/x64dbg/x64dbg/issues/1379

All seems to be "style.css"'s problem

**Comment by techbliss** [comment]
Can you check the latest pushed fix

**Comment by gmastergreatee** [comment]
Sure, I'll check it out

**Comment by ghost** [comment]
Menu color problem
![asdasd2](https://cloud.githubusercontent.com/assets/17880848/21287442/a0210366-c491-11e6-8d7f-43fca7db542d.gif)

**Comment by techbliss** [comment]
i pushed wrong one, please check lastest style.css

**Comment by techbliss** [comment]
Fixed
